# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kfk < Formula
  desc "A modern Kafka CLI tool"
  homepage "https://github.com/sudovishal/kfk"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sudovishal/kfk/releases/download/v0.1.3/kfk_darwin_amd64.tar.gz"
      sha256 "79e9568057b4311099cd3995c499084c4090cad4bde9c049994c6f64e8425138"

      define_method(:install) do
        bin.install "kfk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sudovishal/kfk/releases/download/v0.1.3/kfk_darwin_arm64.tar.gz"
      sha256 "0d754b55084f1965fe22338a22d9a8c61f9feecd50efd12d2791a67816e9acec"

      define_method(:install) do
        bin.install "kfk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sudovishal/kfk/releases/download/v0.1.3/kfk_linux_amd64.tar.gz"
      sha256 "8fb90fde1b7a55b53d904c115e6c59d0c15e8001eab3f07e63a08ae1fd6d30ab"
      define_method(:install) do
        bin.install "kfk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sudovishal/kfk/releases/download/v0.1.3/kfk_linux_arm64.tar.gz"
      sha256 "b7670a0ebb672d547c353c41562e938c2123e0b3a685ef59cc96911b7b541830"
      define_method(:install) do
        bin.install "kfk"
      end
    end
  end

  test do
    system "#{bin}/kfk", "version"
  end
end
